version: "3"
services:
  redis:
    image: redis:alpine3.19
    restart: always
    expose:
      - 6379
  api:
    build:
      context: .
      target: api
    image: hdii_tools__api
    restart: always
    depends_on:
      - redis
    environment:
      - HDII__GENERIC__USER_AGENT=${HDII__GENERIC__USER_AGENT-docker}-api
      - HDII__API__BIND_ADDRESS=0.0.0.0:3000
      - HDII__API__REDIS_DB=${HDII__API__REDIS_DB-0}
      - HDII__API__REDIS_HOST=${HDII__API__REDIS_HOST-redis}
      - HDII__API__REDIS_PORT=${HDII__API__REDIS_PORT-6379}
      - HDII__API__HELLDIVERS_API=${HDII__API__REMOTE_HOST-https://api.live.prod.thehelldiversgame.com/api}
      - HDII__API__DIVEHARDER_API=${HDII__API__DIVEHARDER_API-https://api.diveharder.com}
    expose:
      - 3000
  bot:
    build:
      context: .
      target: bot
    image: hdii_tools__bot
    restart: always
    depends_on:
      - api
    environment:
      - HDII__GENERIC__USER_AGENT=${HDII__GENERIC__USER_AGENT-docker}-bot
      - HDII__API__REDIS_DB=${HDII__API__REDIS_DB-0}
      - HDII__API__REDIS_HOST=${HDII__API__REDIS_HOST-redis}
      - HDII__API__REDIS_PORT=${HDII__API__REDIS_PORT-6379}
      - HDII__BOT__API=${HDII__BOT__API-http://api:3000/api}
      - HDII__BOT__DB_DRIVER=${HDII__BOT__DB_DRIVER-}
      - HDII__BOT__DB_DSN=${HDII__BOT__DB_DSN-}
      - HDII__BOT__TOKEN=${HDII__BOT__TOKEN}
    volumes:
      - ${HDII__BOT__VOLUME_PATH_HOST}:${HDII__BOT__VOLUME_PATH_CONTAINER}
  updater:
    build:
      context: .
      target: updater
    image: hdii_tools__updater
    restart: always
    depends_on:
      - api
      - redis
    environment:
      - HDII__GENERIC__USER_AGENT=${HDII__GENERIC__USER_AGENT-docker}-updater
      - HDII__API__REDIS_DB=${HDII__API__REDIS_DB-0}
      - HDII__API__REDIS_HOST=${HDII__API__REDIS_HOST-redis}
      - HDII__API__REDIS_PORT=${HDII__API__REDIS_PORT-6379}
      - HDII__BOT__API=${HDII__BOT__API-http://api:3000/api}
      - HDII__UPDATER__INFLUXDB__URL=${HDII__UPDATER__INFLUXDB__URL}
      - HDII__UPDATER__INFLUXDB__TOKEN=${HDII__UPDATER__INFLUXDB__TOKEN}
